# Start from a balena python3 image; build version is needed for RPi.GPIO
FROM balenalib/raspberrypi4-64-debian-python

RUN pip install rpi-gpio
RUN pip install setuptools
RUN pip install pyserial
RUN pip install click
RUN pip install rak811

COPY pyrak811-balena.py /opt/rak811/

WORKDIR /opt/rak811

CMD ["./pyrak811-balena.py"]

